# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uh1CpgJQYAzEudrhxELq4SbHmWKnLCv
"""

import pandas as pd

l1 = [10,20,30]

s1 =  pd.Series(data=l1)
s1

s3 = pd.Series(['A','D','I','T','I'])
s3

s4 = pd.Series(data = [10,20,30,40],
               index = ['A','B','C','D'],
               dtype=object)
s4

s5 = s4.astype('float64')
s5

s5.shape

s5.size

s5['A']

#s5['A':'C']

s6 = pd.Series((10,20))
s6

s8 = pd.Series({'num1': 10, 'num2':20, 'num3':30}, index = ['A','B','C'])
s8

s9 = pd.Series(data=[10,20,None, None, 30,40,50,None])
s9

s9.isnull()

(s9.isnull().sum())/ len(s9)*100

(s9.isnull().sum())/(s9.size)*100

(s9.isnull().sum())/(s9.shape[0])*100

s9.info()

s9.describe()

s10 = pd.Series([10,20,30,40,50])
s10

s10.values

s10.index

s10+5

s10-5

s10 = s10*5

s10>20

s10[s10>20]

