# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEG6OnMhUBAhD203OoDayEz8QYkG6Q_n
"""

import pandas as pd

d1 ={
    'sid': [1,2,3,4,5],
    'sname':['ram', 'sahm','kirti','siya', 'radha'],
    'marks':[80,70,50,40,90]


}
df1 = pd.DataFrame(data = d1)
df1

df1 = pd.DataFrame(data = d1, index = ['std1','std2','std3','std4','std5'])
df1

df1.loc['std1'] #loc work on row level index

df1.loc['std1':'std2']

#df1.loc['sname'] #KeyError: 'sname'

df1['sname']

# : -> access all rows
# iloc colun level index
df1.iloc[:,0]

#df1.iloc[:,0,2]

d2 ={
    'sid': [1,2,3,4,5],
    'sname':['ram', 'sahm','kirti','siya', 'radha'],
    'marks':[80,70,60,70,None],
    'age': [22,23,24,25, None],
    'city':['pune', 'pandharpur', 'solapur', 'ayodhya',None]


}

df2 = pd.DataFrame(data=d2)

df2.isnull().sum()

df2.isnull().sum().sum()

# fill data using mean mode median
# mean ->

s1 = pd.Series([10,20,30])
s1.mean()

s2 = pd.Series([10,20,40])
s2.mean()

s1.median()

s2.median()

df2.fillna(10)

df2

# method : {{'backfill', 'bfill', 'ffill', None}}, default None
# Method to use for filling holes in reindexed Series:

df2.fillna(method = 'bfill' ,axis = 0)

df2.fillna(method = 'ffill', axis = 1)

df2

df2['age'].fillna(df2['age'].mean())

df2['age'].fillna(df2['age'].mean())

df2['marks'].fillna(df2['marks'].mean())

df2

#df2['marks'] = df2['marks'].fillna(df2['mrks'].mean().inplace = True)

#df2['city'].fillna(df2['city'].mode()[0])

df3 ={
    'sid': [1,2,3,4,5],
    'sname':['ram', 'sahm','kirti','siya', 'radha'],
    'marks':[80,70,50,40,90]


}
df3 = pd.DataFrame(data = df3)
df3

df3.dropna(axis=1)

#df3.drop(column=['sname','marks'])

df3.head(2)

df3.tail(2)

df3.shape

df3.size

df3.info()

df3.describe()

