# -*- coding: utf-8 -*-
"""matplotlib Day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jHFuP7c6d_b-RMo23-oSry28SPJIzrU
"""

# import matplotlib as plt
import matplotlib.pyplot as plt
import numpy as np

x = np.array([1,2,3,4,5,6,7])
y = np.array([10,20,70,40,50,60,130])
plt.plot(x,y, "p-", mfc = "red" , )
plt.title("share market")

plt.xlabel("No. of day")
plt.ylabel("share price")

# plt.grid(axis="both", color="red", ls = "dashed")
plt.show()

y = np.array([60,20,10,10])
plt.pie(y,
        labels = ["python", "data science", "java", "cloud"],
        startangle=90,
        explode=[0,0,0,0],
        colors = ['grey', 'yellow', 'black', 'pink'],


        )
plt.legend(loc="upper right", title = "course info", labelcolor = "red", fontsize = "xx-large")
plt.title("course info ")
plt.show()

x1 = np.array([0,1,2,3,4,5])
y1 = np.array([10,20,90,10,50,60])
plt.subplot(1,3,1)
plt.plot(x1,y1)

x1 = np.array([0,1,2,3,4,5])
y1 = np.array([10,20,10,100,50,60])
plt.subplot(1,3,2)


plt.plot(x1,y1)


x1 = np.array([0,1,2,3,4,5])
y1 = np.array([10,20,70,0,50,60])
plt.subplot(1,3,3)


plt.plot(x1,y1)

std = np.array(['ram', 'siya','sham', 'radha'])
marks = np.array([60,80,50,80])

plt.bar(x= std, height = marks, )

out = np.array([10,20,30,40,100,200])
plt.boxplot(out)
plt.title("Box Plot Example")
plt.ylabel("Values")
plt.show()

data = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]

plt.boxplot(data)

plt.show()

